---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-demo
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: nginx-demo
  labels:
    cilium.io/lb-pool: pool-1
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-app1-route
  namespace: app1
spec:
  parentRefs:
    - name: nginx-gateway
      namespace: nginx-demo
  hostnames:
    - "app1.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nginx-app1
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-app2-route
  namespace: app2
spec:
  parentRefs:
    - name: nginx-gateway
      namespace: nginx-demo
  hostnames:
    - "app2.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nginx-app2
          port: 80
